apiVersion : apps/v1
kind: Deployment
metadata:
  name: phpipelinesjavascriptdocker 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: phpipelinesjavascriptdocker 
    spec:
      containers:
        - name: phpipelinesjavascriptdocker 
          image: philip1979containerregistry.azurecr.io/phpipelinesjavascriptdocker
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m